GruppL_IK073G_ht19/Models/Persons.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppL_IK073G_ht19.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.Educations = new HashSet<Educations>();
            this.Employments = new HashSet<Employments>();
            this.key_abilitiy = new HashSet<key_abilitiy>();
            this.Languages1 = new HashSet<Languages>();
            this.Person_Expertise = new HashSet<Person_Expertise>();
        }
    
        public int Person_id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Adress { get; set; }
        public string Phonenumber { get; set; }
        public string Email { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> Driver_license { get; set; }
        public string Profile_text { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Educations> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employments> Employments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<key_abilitiy> key_abilitiy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Languages> Languages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_Expertise> Person_Expertise { get; set; }
    }
}

GruppL_IK073G_ht19/ViewModels/PersonViewModels.cs
using GruppL_IK073G_ht19.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GruppL_IK073G_ht19.ViewModels
{
    public class PersonViewModels
    {
        public Persons Persons { get; set; }
        public List <Educations>  Educations { get; set; }
        public List <Employments> Employments { get; set; }
        public List <key_abilitiy> key_Abilitiys { get; set; }
        public List <Languages> Languages { get; set; }
        public List <Expertises> Expertises{ get; set; }
        public List <Competences> Competences { get; set; }
        public List <Person_Expertise> PersonExpertises { get; set; }
    }
}

GruppL_IK073G_ht19/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using GruppL_IK073G_ht19.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using System.Text;
using iTextSharp.text.html.simpleparser;
using GruppL_IK073G_ht19.ViewModels;

namespace GruppL_IK073G_ht19.Controllers
{
    public class PersonsController : Controller
    {
        
        private gruppldbEntities1 db = new gruppldbEntities1();

        // GET: Persons
        public ActionResult Index()
        {
            return View(db.Persons.ToList());
        }

        public ActionResult CIndex()
        {
            return View(db.Persons.ToList());
        }

        // GET: Persons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            PersonsOperation p = new PersonsOperation();
            var viewModel = new PersonViewModels
            {
                Persons = persons,
                Educations=p.Educations(id),
                Employments = p.FindEmployment(id),
                key_Abilitiys=p.KeyAbilitiys(id),
                PersonExpertises=p.PersonExpertises(id),
                Languages=p.Languages(id),
                Competences=p.Competenses(id)
            };


            return View(viewModel);
        }

        public ActionResult CDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            PersonsOperation p = new PersonsOperation();
            var viewModel = new PersonViewModels
            {
                Persons = persons,
                Educations = p.Educations(id),
                Employments = p.FindEmployment(id),
                key_Abilitiys = p.KeyAbilitiys(id),
                PersonExpertises = p.PersonExpertises(id),
                Languages = p.Languages(id)

            };


            return View(viewModel);
        }
        // GET: Persons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Person_id,FirstName,LastName,Adress,Phonenumber,Email,Birthdate,Nationality,Driver_license,Profile_text")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                db.Persons.Add(persons);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(persons);
        }

        // GET: Persons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            //Educations educations = db.Educations

            return View(persons);


        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Person_id,FirstName,LastName,Adress,Phonenumber,Email,Birthdate,Nationality,Driver_license,Profile_text")] Persons persons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(persons).State = EntityState.Modified;
                db.SaveChanges();
               return RedirectToAction("Edit/1");
            }
            return View(persons);
        }

        // GET: Persons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persons persons = db.Persons.Find(id);
            if (persons == null)
            {
                return HttpNotFound();
            }
            return View(persons);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Persons persons = db.Persons.Find(id);
            db.Persons.Remove(persons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Exportera till PDF
        [HttpPost]
        [ValidateInput(false)]
        public FileResult Export(string pdfHtml)
        {
           // var cssText = "~/Content/Site.css"
            using (MemoryStream stream = new System.IO.MemoryStream())
            {
                StringReader sr = new StringReader(pdfHtml);
                Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 100f, 0f);
                PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
                pdfDoc.Open();
                XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                pdfDoc.Close();
                return File(stream.ToArray(), "application/pdf", "Grid.pdf");
            }
        }


    }
}

GruppL_IK073G_ht19/Views/Persons/CDetails.cshtml
@model GruppL_IK073G_ht19.ViewModels.PersonViewModels
@*@model GruppL_IK073G_ht19.Models.Persons*@

@* Här är det något som ska ändras... Sen borde det kanske gå *@

@{
    ViewBag.Title = "CDetails";

    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
}
<div class="jumbotron">

    <h2 class="aLink">@Html.DisplayFor(model => model.Persons.FirstName) @Html.DisplayFor(model => model.Persons.LastName)</h2>
    <hr />

    <div id="pdf">

        <dl class="dl-horizontal">
            <dt>
                Förnamn:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.FirstName)
            </dd>

            <dt>
                Efternamn:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.LastName)
            </dd>

            <dt>
                Adress:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Adress)
            </dd>

            <dt>
                Telefonnummer:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Phonenumber)
            </dd>

            <dt>
                E-post:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Email)
            </dd>

            <dt>
                Födelsedata:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Birthdate)
            </dd>

            <dt>
                Nationalitet:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Nationality)
            </dd>

            <dt>
                Körkort:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Persons.Driver_license)
            </dd>

            <dt>
                Profiltext:
            </dt>

            <dd>
                <textarea>
                            @Html.DisplayFor(model => model.Persons.Profile_text)

                        </textarea>
            </dd>
        </dl>
    </div>

</div>


<table class="table">
    <tr>
        <th>
            Arbetsuppgifter
        </th>

        <th>
            Startdatum
        </th>
        <th>
            Slutdatum
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Employments)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Assignments)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start_date)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End_date)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Skola
        </th>

        <th>
            Program
        </th>
        <th>
            Diplom
        </th>
        <th>
            Startdatum
        </th>
        <th>
            Slutdatum
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Educations)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Educational_institution)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Educational_program)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diploma)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Start_date)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.End_date)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Kärnförmågor
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.key_Abilitiys)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.abilitiy)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Expertis
        </th>
        <th>
            Gradering
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model.PersonExpertises)
    {

        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Expertises)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Grade)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Språk
        </th>
        <th>
            Gradering
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model.Languages)
    {

        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Language)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Grade)

            </td>
        </tr>
    }

</table>

<div>
    <br />
    <a href="https://www.linkedin.com">
        <img alt="Linkedin" src="~/Content/linkedin.png" width="30" height="30">
    </a>
    <a href="https://www.github.com">
        <img border="0" alt="Github" src="~/Content/github-logo.png" width="30" height="30">
    </a>
</div>
<br />
<p>
    @Html.ActionLink("Tillbaka", "CIndex")
</p>

GruppL_IK073G_ht19/Views/Persons/CIndex.cshtml
@model IEnumerable<GruppL_IK073G_ht19.Models.Persons>

@{
    ViewBag.Title = "CIndex";
    <link rel="stylesheet" type="text/css" href="~/Content/PersonSearch.css">

}

<h2>Här kan du se  frilansare som söker uppdragsgivare just nu:</h2>

<input type="text" id="myInput" onkeyup="searchTable()" placeholder="Sök">
    <table id="myTable" class="table">
    <tr>
        <th>
            Förnamn
        </th>
        <th>
            Efternamn
        </th>
        <th>
            Adress
        </th>
        <th>
            Telefonnummer
        </th>
        <th>
            E-post
        </th>
        <th>
            Födelsedatum
        </th>
        <th>
            Nationalitet
        </th>
        <th>
            Körkort
        </th>
        <th>
            Beskrivning
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Birthdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Driver_license)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Profile_text)
            </td>
            <td>

                @Html.ActionLink("Visa profil", "CDetails", new { id = item.Person_id })

            </td>
        </tr>
    }

</table>

    <script>
        function searchTable() {

            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");


            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td");
                for (j = 0; j < td.length; j++) {
                    let tdata = td[j];
                    if (tdata) {
                        if (tdata.innerHTML.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                            break;
                        } else {
                            tr[i].style.display = "none";
                        }
                    }
                }
            }
        }
    </script>

GruppL_IK073G_ht19/Views/Persons/Create.cshtml
@model GruppL_IK073G_ht19.Models.Persons

@{
    ViewBag.Title = "Create";
}

<h2>Skapa Profil</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    <h4>Fyll i dina uppgifter</h4>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label name="lblFN" id="control-label col-md-2" class="control-label col-md-2"> <b>Förnamn</b> </label>
        <div class="col-md-10">

            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })

            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblFLN" id="control-label col-md-2" class="control-label col-md-2"> <b>Efternamn</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblAd" id="control-label col-md-2" class="control-label col-md-2"> <b>Adress</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblPn" id="control-label col-md-2" class="control-label col-md-2"> <b>Telefonnummer</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phonenumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phonenumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblEm" id="control-label col-md-2" class="control-label col-md-2"> <b>E-post</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblBd" id="control-label col-md-2" class="control-label col-md-2"> <b>Födelsedata</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblN" id="control-label col-md-2" class="control-label col-md-2"> <b>Nationalitet</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label name="lblDL" id="control-label col-md-2" class="control-label col-md-2"> <b>Körkort</b> </label>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Driver_license)
                @Html.ValidationMessageFor(model => model.Driver_license, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <label name="lblPT" id="control-label col-md-2" class="control-label col-md-2"> <b>Profiltext</b> </label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Profile_text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Profile_text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Skapa profil" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Visa lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GruppL_IK073G_ht19/Views/Persons/Delete.cshtml
@model GruppL_IK073G_ht19.Models.Persons

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Driver_license)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Driver_license)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profile_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profile_text)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GruppL_IK073G_ht19/Views/Persons/Details.cshtml
@model GruppL_IK073G_ht19.ViewModels.PersonViewModels
@*@model GruppL_IK073G_ht19.Models.Persons*@

@* , new {id=item.Person_id} *@

@{
    ViewBag.Title = "Details";

    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
}
    <div class="jumbotron">
        
          <h2 class="ProfileName">@Html.DisplayFor(model => model.Persons.FirstName) @Html.DisplayFor(model => model.Persons.LastName)</h2>
          <hr />

            <div id="pdf">

                <dl class="dl-horizontal">
                    <dt>
                        Förnamn:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.FirstName)
                    </dd>

                    <dt>
                        Efternamn:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.LastName)
                    </dd>

                    <dt>
                        Adress:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Adress)
                    </dd>

                    <dt>
                        Telefonnummer:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Phonenumber)
                    </dd>

                    <dt>
                        E-post:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Email)
                    </dd>

                    <dt>
                        Födelsedata:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Birthdate)
                    </dd>

                    <dt>
                        Nationalitet:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Nationality)
                    </dd>

                    <dt>
                        Körkort:
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Persons.Driver_license)
                    </dd>

                    <dt>
                        Profiltext:
                    </dt>

                    <dd>
                        <article>


                            @Html.DisplayFor(model => model.Persons.Profile_text)
                        </article>

                    </dd>
                </dl>
            </div>
     
    </div>


<table class="table">
    <tr>
        <th>
            Arbetsuppgifter
        </th>

        <th>
            Startdatum
        </th>
        <th>
            Slutdatum
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Employments)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Assignments)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Start_date)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.End_date)

    </td>
</tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Skola
        </th>

        <th>
            Program
        </th>
        <th>
            Diplom
        </th>
        <th>
            Startdatum
        </th>
        <th>
            Slutdatum
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Educations)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Educational_institution)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Educational_program)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Diploma)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Start_date)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.End_date)

    </td>
</tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Kärnförmågor
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.key_Abilitiys)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.abilitiy)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Expertis
        </th>
        <th>
            Gradering
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model.PersonExpertises)
    {

        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Expertises)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Grade)

            </td>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            Språk
        </th>
        <th>
            Gradering
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model.Languages)
    {

        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Language)

            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Grade)

            </td>
        </tr>
    }

</table>

<div>
    <br />
    <a href="https://www.linkedin.com">
        <img alt="Linkedin" src="~/Content/linkedin.png" width="30" height="30">
    </a>
    <a href="https://www.github.com">
        <img border="0" alt="Github" src="~/Content/github-logo.png" width="30" height="30">
    </a>
</div>


@using (Html.BeginForm("Export", "Persons", FormMethod.Post))
{
    <input type="hidden" name="pdfHtml" />
    <input type="submit" class="buttonPdf" id="btnSubmit" value="Exportera till PDF" />
}
    <br />

<a href="/Persons/Index/1"><button class="logout">Tillbaka</button></a>
<a href="/Persons/Edit/1"><button class="logout">Redigera</button></a>
   
        
    
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='pdfHtml']").val($("#pdf").html());

        });
    });
</script>